# Generated by Django 5.2.9 on 2025-12-25 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Уникальный инвентарный номер экспоната', max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('acquisition_date', models.DateField(verbose_name='Дата поступления')),
                ('status', models.CharField(choices=[('ON_DISPLAY', 'На выставке'), ('IN_RESTORATION', 'На реставрации'), ('IN_STORAGE', 'В запаснике'), ('ON_LOAN', 'В другом музее')], default='IN_STORAGE', max_length=20, verbose_name='Статус')),
                ('current_location', models.CharField(help_text='Зал, музей, реставрационная мастерская и т.д.', max_length=255, verbose_name='Текущее местоположение')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор/создатель')),
                ('creation_date', models.CharField(blank=True, help_text='Может быть текстом, например "XVIII век"', max_length=100, verbose_name='Дата создания')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='Материал')),
                ('dimensions', models.CharField(blank=True, max_length=255, verbose_name='Размеры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('STATUS_CHANGE', 'Изменение статуса'), ('LOCATION_CHANGE', 'Изменение местоположения'), ('SENT_TO_RESTORATION', 'Отправка на реставрацию'), ('RETURNED_FROM_RESTORATION', 'Возврат с реставрации'), ('SENT_TO_STORAGE', 'Перемещение в запасник'), ('SENT_ON_LOAN', 'Отправка в другой музей'), ('RETURNED_FROM_LOAN', 'Возврат из другого музея'), ('OTHER', 'Другое')], max_length=30, verbose_name='Тип действия')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='В статус')),
                ('from_location', models.CharField(blank=True, max_length=255, verbose_name='Откуда')),
                ('to_location', models.CharField(blank=True, max_length=255, verbose_name='Куда')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('notes', models.TextField(verbose_name='Примечания')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='museum.exhibit', verbose_name='Экспонат')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал истории',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibits/%Y/%m/%d/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('is_main', models.BooleanField(default=False, help_text='Отображается в каталоге', verbose_name='Главное фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='museum.exhibit', verbose_name='Экспонат')),
            ],
            options={
                'verbose_name': 'Фотография экспоната',
                'verbose_name_plural': 'Фотографии экспонатов',
                'ordering': ['-is_main', '-uploaded_at'],
            },
        ),
    ]
